// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Expense struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Amount      string
	Title       string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedBy   uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GroupExpense struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Amount      string
	GroupID     uuid.UUID
	CreatedBy   uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GroupExpenseParticipant struct {
	ID             uuid.UUID
	GroupExpenseID uuid.UUID
	UserID         uuid.UUID
	Amount         string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type GroupMember struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
	AddedAt sql.NullTime
}

type GroupMembersDebt struct {
	ID        uuid.UUID
	FromUser  uuid.UUID
	ToUser    uuid.UUID
	GroupID   uuid.UUID
	ExpenseID uuid.UUID
	Amount    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PasswordToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type SimplifiedTransaction struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	FromUser uuid.UUID
	ToUser   uuid.UUID
	Amount   string
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	TokenVersion sql.NullInt32
	LastLoggedIn sql.NullTime
	AccessLevel  string
}
