// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type PasswordToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	TokenVersion sql.NullInt32
	LastLoggedIn sql.NullTime
	AccessLevel  string
}
